
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
    searched_directories:
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 25.5.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
    searched_directories:
      - "/opt/homebrew/bin/gmake"
      - "/opt/homebrew/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/System/Cryptexes/App/usr/bin/gmake"
      - "/usr/bin/gmake"
      - "/bin/gmake"
      - "/usr/sbin/gmake"
      - "/sbin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/gmake"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/gmake"
      - "/pkg/env/global/bin/gmake"
      - "/Applications/iTerm.app/Contents/Resources/utilities/gmake"
      - "/opt/homebrew/bin/make"
      - "/opt/homebrew/sbin/make"
      - "/usr/local/bin/make"
      - "/System/Cryptexes/App/usr/bin/make"
    found: "/usr/bin/make"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:66 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
    searched_directories:
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
      CMAKE_INSTALL_PREFIX: "/usr/local"
  -
    kind: "find-v1"
    backtrace:
      - "CMakeLists.txt:13 (find_program)"
    mode: "program"
    variable: "VASM_EXECUTABLE"
    description: "Path to the vasm m68k assembler (vasmm68k_mot)"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "vasmm68k_mot"
      - "vasmm68k_mot_win32"
      - "vasmm68k_mot_win64"
      - "vasmm68k_mot.exe"
      - "vasmm68k_mot_win32.exe"
      - "vasmm68k_mot_win64.exe"
    candidate_directories:
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/bin/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/sbin/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/homebrew/"
      - "/usr/local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/"
      - "/usr/bin/"
      - "/usr/sbin/"
      - "/usr/"
      - "/bin/"
      - "/sbin/"
      - "/usr/X11R6/bin/"
      - "/usr/X11R6/sbin/"
      - "/usr/X11R6/"
      - "/usr/pkg/bin/"
      - "/usr/pkg/sbin/"
      - "/usr/pkg/"
      - "/opt/bin/"
      - "/opt/sbin/"
      - "/opt/"
      - "/sw/bin/"
      - "/sw/sbin/"
      - "/sw/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/opt/local/"
      - "/Applications/"
    searched_directories:
      - "/opt/homebrew/bin/vasmm68k_mot"
      - "/opt/homebrew/sbin/vasmm68k_mot"
    found: "/usr/local/bin/vasmm68k_mot"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
      CMAKE_INSTALL_PREFIX: "/usr/local"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr"
        - "/"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr/X11R6"
        - "/usr/pkg"
        - "/opt"
        - "/sw"
        - "/opt/local"
      CMAKE_SYSTEM_APPBUNDLE_PATH:
        - "/Applications"
  -
    kind: "find-v1"
    backtrace:
      - "CMakeLists.txt:18 (find_program)"
    mode: "program"
    variable: "VLINK_EXECUTABLE"
    description: "Path to the vlink linker"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "vlink"
      - "vlink.exe"
    candidate_directories:
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/bin/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/sbin/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/homebrew/"
      - "/usr/local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/"
      - "/usr/bin/"
      - "/usr/sbin/"
      - "/usr/"
      - "/bin/"
      - "/sbin/"
      - "/usr/X11R6/bin/"
      - "/usr/X11R6/sbin/"
      - "/usr/X11R6/"
      - "/usr/pkg/bin/"
      - "/usr/pkg/sbin/"
      - "/usr/pkg/"
      - "/opt/bin/"
      - "/opt/sbin/"
      - "/opt/"
      - "/sw/bin/"
      - "/sw/sbin/"
      - "/sw/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/opt/local/"
      - "/Applications/"
    searched_directories:
      - "/opt/homebrew/bin/vlink"
      - "/opt/homebrew/sbin/vlink"
      - "/usr/local/bin/vlink"
      - "/System/Cryptexes/App/usr/bin/vlink"
      - "/usr/bin/vlink"
      - "/bin/vlink"
      - "/usr/sbin/vlink"
      - "/sbin/vlink"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/vlink"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/vlink"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/vlink"
      - "/pkg/env/global/bin/vlink"
      - "/Applications/iTerm.app/Contents/Resources/utilities/vlink"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/bin/vlink"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/sbin/vlink"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/vlink"
      - "/opt/homebrew/bin/vlink"
      - "/opt/homebrew/sbin/vlink"
      - "/opt/homebrew/vlink"
      - "/usr/local/bin/vlink"
      - "/usr/local/sbin/vlink"
      - "/usr/local/vlink"
      - "/usr/bin/vlink"
      - "/usr/sbin/vlink"
      - "/usr/vlink"
      - "/bin/vlink"
      - "/sbin/vlink"
      - "/usr/X11R6/bin/vlink"
      - "/usr/X11R6/sbin/vlink"
      - "/usr/X11R6/vlink"
      - "/usr/pkg/bin/vlink"
      - "/usr/pkg/sbin/vlink"
      - "/usr/pkg/vlink"
      - "/opt/bin/vlink"
      - "/opt/sbin/vlink"
      - "/opt/vlink"
      - "/sw/bin/vlink"
      - "/sw/sbin/vlink"
      - "/sw/vlink"
      - "/opt/local/bin/vlink"
      - "/opt/local/sbin/vlink"
      - "/opt/local/vlink"
      - "/Applications/vlink"
      - "/opt/homebrew/bin/vlink.exe"
      - "/opt/homebrew/sbin/vlink.exe"
      - "/usr/local/bin/vlink.exe"
      - "/System/Cryptexes/App/usr/bin/vlink.exe"
      - "/usr/bin/vlink.exe"
      - "/bin/vlink.exe"
      - "/usr/sbin/vlink.exe"
      - "/sbin/vlink.exe"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/vlink.exe"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/vlink.exe"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/vlink.exe"
      - "/pkg/env/global/bin/vlink.exe"
      - "/Applications/iTerm.app/Contents/Resources/utilities/vlink.exe"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/bin/vlink.exe"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/sbin/vlink.exe"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/vlink.exe"
      - "/opt/homebrew/bin/vlink.exe"
      - "/opt/homebrew/sbin/vlink.exe"
      - "/opt/homebrew/vlink.exe"
      - "/usr/local/bin/vlink.exe"
      - "/usr/local/sbin/vlink.exe"
      - "/usr/local/vlink.exe"
      - "/usr/bin/vlink.exe"
      - "/usr/sbin/vlink.exe"
      - "/usr/vlink.exe"
      - "/bin/vlink.exe"
      - "/sbin/vlink.exe"
      - "/usr/X11R6/bin/vlink.exe"
      - "/usr/X11R6/sbin/vlink.exe"
      - "/usr/X11R6/vlink.exe"
      - "/usr/pkg/bin/vlink.exe"
      - "/usr/pkg/sbin/vlink.exe"
      - "/usr/pkg/vlink.exe"
      - "/opt/bin/vlink.exe"
      - "/opt/sbin/vlink.exe"
      - "/opt/vlink.exe"
      - "/sw/bin/vlink.exe"
      - "/sw/sbin/vlink.exe"
      - "/sw/vlink.exe"
      - "/opt/local/bin/vlink.exe"
      - "/opt/local/sbin/vlink.exe"
      - "/opt/local/vlink.exe"
      - "/Applications/vlink.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
      CMAKE_INSTALL_PREFIX: "/usr/local"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr"
        - "/"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr/X11R6"
        - "/usr/pkg"
        - "/opt"
        - "/sw"
        - "/opt/local"
      CMAKE_SYSTEM_APPBUNDLE_PATH:
        - "/Applications"
...

---
events:
  -
    kind: "find-v1"
    backtrace:
      - "CMakeLists.txt:18 (find_program)"
    mode: "program"
    variable: "VLINK_EXECUTABLE"
    description: "Path to the vlink linker"
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "vlink"
      - "vlink.exe"
    candidate_directories:
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Applications/iTerm.app/Contents/Resources/utilities/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/bin/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/sbin/"
      - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/homebrew/"
      - "/usr/local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/"
      - "/usr/bin/"
      - "/usr/sbin/"
      - "/usr/"
      - "/bin/"
      - "/sbin/"
      - "/usr/X11R6/bin/"
      - "/usr/X11R6/sbin/"
      - "/usr/X11R6/"
      - "/usr/pkg/bin/"
      - "/usr/pkg/sbin/"
      - "/usr/pkg/"
      - "/opt/bin/"
      - "/opt/sbin/"
      - "/opt/"
      - "/sw/bin/"
      - "/sw/sbin/"
      - "/sw/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/opt/local/"
      - "/Applications/"
    searched_directories:
      - "/opt/homebrew/bin/vlink"
      - "/opt/homebrew/sbin/vlink"
    found: "/usr/local/bin/vlink"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Applications/iTerm.app/Contents/Resources/utilities"
      CMAKE_INSTALL_PREFIX: "/usr/local"
      CMAKE_SYSTEM_PREFIX_PATH:
        - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr"
        - "/"
        - "/opt/homebrew"
        - "/usr/local"
        - "/usr/X11R6"
        - "/usr/pkg"
        - "/opt"
        - "/sw"
        - "/opt/local"
      CMAKE_SYSTEM_APPBUNDLE_PATH:
        - "/Applications"
...
